services:
    database:
        container_name: "postgres-container"
        image: "postgres:17.0-alpine3.20"
        env_file:
            - ../.env.development
        environment:
            POSTGRES_USER: localuser
            POSTGRES_PASSWORD: localpassword
            POSTGRES_DB: localdb
        ports:
            - "5432:5432"
